### ISSUE TITLE
为什么页面里没有‘订阅’按钮？

### ISSUE THREAD

**Issue by stillsilly** [RexFang/translation_bing#1]
你好，在博客园看到你写的教程，跟着一步一步操作到‘注册页面，点击页面右侧的注册按钮，然后勾选同意协议，再点击注册按钮。’时，https://datamarket.azure.com/dataset/bing/microsofttranslator
这个页面右边并没有订阅按钮，必应关闭了这个服务吗  你那篇文章发表日期也就十几天前呢  还是我打开方式不对，应该怎么打开  能帮我瞅瞅吗……谢谢

**Comment by RexFang** [comment]
你好，必应翻译的服务已经被停止了，需要的话，你可以联系微软那边的客服，让他们协助你解决。代码是16年10月份写的，前一段时间才整理到博客上，周知。


fangruitao.work@foxmail.com
 
发件人： 周羊羊
发送时间： 2017-04-05 15:36
收件人： RexFang/translation_bing
抄送： Subscribed
主题： [RexFang/translation_bing] 为什么页面里没有‘订阅’按钮？ (#1)
你好，在博客园看到你写的教程，跟着一步一步操作到‘注册页面，点击页面右侧的注册按钮，然后勾选同意协议，再点击注册按钮。’时，https://datamarket.azure.com/dataset/bing/microsofttranslator
这个页面右边并没有订阅按钮，必应关闭了这个服务吗 你那篇文章发表日期也就十几天前呢 还是我打开方式不对，应该怎么打开 能帮我瞅瞅吗……谢谢

**Comment by stillsilly** [comment]
昂 好的  多谢回复

**Comment by RexFang** [comment]
Bing 翻译在台湾有办事处，你可以尝试联系一下。



fangruitao.work@foxmail.com
 
发件人： 周羊羊
发送时间： 2017-04-07 13:47
收件人： RexFang/translation_bing
抄送： RexFang; Comment
主题： Re: [RexFang/translation_bing] 为什么页面里没有‘订阅’按钮？ (#1)
昂 好的 多谢回复
―
